spring.application.name=inven-track

# Base de datos en memoria (H2) para desarrollo
spring.datasource.url=jdbc:h2:mem:inventrackdb
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
